<ul>
<li><a href="index.php"><span class="bracket">[ </span>Home<span class="bracket"> ]</span></a></li><li class="dropdown">
    <a href="hw.php?style=1" class="dropbtn"><span class="bracket">[ </span>Work<span class="bracket"> ]</span></a>
    <ul class="dropdown-content">
      <li><a href="https://studenthome.hku.nl/~inger.smit/hw.php?dir=Animatie~Raf_Croonen!&style=1">Animatie</a></li>
      <li><a href="https://studenthome.hku.nl/~inger.smit/hw.php?dir=Art_Media_and_Me~Sonja_van_Vuure!&style=1">Art Media and Me</a></li>
    </ul>
<li><a href="cv.php"><span class="bracket">[ </span>CV<span class="bracket"> ]</span></a></li></li>
</ul>