<ul>
<li><a href="index.php"><span class="bracket">[ </span>Home<span class="bracket"> ]</span></a></li><li class="dropdown">
    <a href="hw.php?style=1" class="dropbtn"><span class="bracket">[ </span>Work<span class="bracket"> ]</span></a>
    <ul class="dropdown-content">
      <li><a href="https://store.steampowered.com/app/2975750/Picterra/">Picterra</a></li>
    </ul>
<li><a href="cv.php"><span class="bracket">[ </span>CV<span class="bracket"> ]</span></a></li></li>
</ul>